-- Practice challenges for beginners
-- Try to solve before checking online

-- Challenge 1:
-- Show all students with their department name.
-- Hint: use JOIN between students and departments.

-- Write your query here:


-- Challenge 2:
-- Count students in each course.
-- Hint: use GROUP BY.

-- Write your query here:


-- Challenge 3:
-- Create a new table called teachers.
-- Columns: teacher_id, full_name, email, department_id.
-- Add PRIMARY KEY and FOREIGN KEY.

-- Write your CREATE TABLE here:


-- Challenge 4:
-- Create a view that shows:
-- student full name + department + course.

-- Write your CREATE VIEW here:


-- Bonus:
-- Add one index that can make search faster.
-- Explain in one sentence why.


-- =====================================================
-- Short Project Starter: Mini Student Management
-- Goal: practice TABLE + FK + INSERT + JOIN + GROUP BY + VIEW
-- =====================================================

-- Step 1) Create teachers table
-- Hna create table jdida bach n7afdo teachers data.
-- TODO: run this block

CREATE TABLE teachers (
	teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	full_name VARCHAR2(100) NOT NULL,
	email VARCHAR2(100) NOT NULL,
	department_id NUMBER,
	CONSTRAINT pk_teachers PRIMARY KEY (teacher_id),
	CONSTRAINT uq_teachers_email UNIQUE (email),
	CONSTRAINT fk_teachers_department
		FOREIGN KEY (department_id)
		REFERENCES departments (department_id)
);


-- Step 2) Add teacher_id to courses
-- Hna ghadi nrabto kol course b teacher.
-- TODO: run this block

ALTER TABLE courses ADD (teacher_id NUMBER);

ALTER TABLE courses
ADD CONSTRAINT fk_courses_teacher
	FOREIGN KEY (teacher_id)
	REFERENCES teachers (teacher_id);


-- Step 3) Insert sample teachers
-- TODO: run this block

INSERT INTO teachers (teacher_id, full_name, email, department_id)
VALUES (1, 'Amina El Fassi', 'amina.teacher@demo.com', 1);

INSERT INTO teachers (teacher_id, full_name, email, department_id)
VALUES (2, 'Karim Tazi', 'karim.teacher@demo.com', 2);

INSERT INTO teachers (teacher_id, full_name, email, department_id)
VALUES (3, 'Sara El Idrissi', 'sara.teacher@demo.com', 3);


-- Step 4) Assign 2 courses per teacher (sample)
-- TODO: adapt if your course IDs are different

UPDATE courses SET teacher_id = 1 WHERE course_id IN (1, 2);
UPDATE courses SET teacher_id = 2 WHERE course_id IN (3);
UPDATE courses SET teacher_id = 3 WHERE course_id IN (4);


-- Step 5) Teacher name + course count
-- Hna JOIN + GROUP BY.
-- TODO: run this query and check result

SELECT t.teacher_id,
			 t.full_name,
			 COUNT(c.course_id) AS course_count
FROM teachers t
LEFT JOIN courses c ON c.teacher_id = t.teacher_id
GROUP BY t.teacher_id, t.full_name
ORDER BY t.teacher_id;


-- Step 6) Create view v_teacher_courses
-- TODO: run this block

CREATE OR REPLACE VIEW v_teacher_courses AS
SELECT t.teacher_id,
			 t.full_name AS teacher_name,
			 c.course_id,
			 c.course_name
FROM teachers t
LEFT JOIN courses c ON c.teacher_id = t.teacher_id;

-- Verify view
SELECT *
FROM v_teacher_courses
ORDER BY teacher_id, course_id;

COMMIT;
