-- Oracle Database teaching schema
-- Run this file first

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_student_courses';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE enrollments CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE courses CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE students CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE departments CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE departments (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_name VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_departments PRIMARY KEY (department_id),
  CONSTRAINT uq_departments_name UNIQUE (department_name)
);

CREATE TABLE students (
  student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(50) NOT NULL,
  last_name VARCHAR2(50) NOT NULL,
  email VARCHAR2(100) NOT NULL,
  age NUMBER(3),
  department_id NUMBER,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_students PRIMARY KEY (student_id),
  CONSTRAINT uq_students_email UNIQUE (email),
  CONSTRAINT ck_students_age CHECK (age >= 16),
  CONSTRAINT fk_students_department
    FOREIGN KEY (department_id)
    REFERENCES departments (department_id)
);

CREATE TABLE courses (
  course_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  course_name VARCHAR2(100) NOT NULL,
  department_id NUMBER,
  CONSTRAINT pk_courses PRIMARY KEY (course_id),
  CONSTRAINT uq_courses_name UNIQUE (course_name),
  CONSTRAINT fk_courses_department
    FOREIGN KEY (department_id)
    REFERENCES departments (department_id)
);

CREATE TABLE enrollments (
  enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  student_id NUMBER NOT NULL,
  course_id NUMBER NOT NULL,
  enrolled_on DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_enrollments PRIMARY KEY (enrollment_id),
  CONSTRAINT uq_enrollment_student_course UNIQUE (student_id, course_id),
  CONSTRAINT fk_enrollments_student
    FOREIGN KEY (student_id)
    REFERENCES students (student_id),
  CONSTRAINT fk_enrollments_course
    FOREIGN KEY (course_id)
    REFERENCES courses (course_id)
);

CREATE INDEX idx_students_last_name ON students (last_name);
CREATE INDEX idx_enrollments_student_id ON enrollments (student_id);
CREATE INDEX idx_enrollments_course_id ON enrollments (course_id);

COMMIT;
